Homework2
IgorErin/shallowSizeTemplate pull request #1
Opened 2022-04-17 10:34 UTC by IgorErin

2022-04-17 12:23 UTC, Ythosa reviewed
Всем привет я ревьюер хочу в жетбреинк ресеч

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +    return when {
Тут можно просто 
```kotlin
IrType.byteSize(): Int = when {
    ...
}
```

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePluginTest/src/test/kotlin/spbu/kotlin/shallow/plugin/ShallowSizeTest.kt
> +    fun `test with custom arguments provider`(size: Int, shallowSize: Int, nameOfTest: String) {
Возможно лучше будет `expectedSize` и `actualSize`

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePluginTest/src/test/kotlin/spbu/kotlin/shallow/plugin/ShallowSizeTest.kt
> +                Arguments.of(1, internalClass.shallowSize(),
Возможно, тут стоит вынести единичку в константу `BOOLEAN_SIZE`

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePluginTest/src/test/kotlin/spbu/kotlin/shallow/plugin/ShallowSizeTest.kt
> +                Arguments.of(2, noBackField.shallowSize(),
А тут `Char.SIZE_BYTES`

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePluginTest/src/test/kotlin/spbu/kotlin/shallow/plugin/ShallowSizeTest.kt
> +        private val baseClass = BaseClass("Hello")
Не совсем понятно, зачем тут выносить инстансы, если они не переиспользуются
```kotlin
Arguments.of(DEFAULT_SIZE, baseClass.shallowSize(),
                    "test for base class failed")
```
или
```kotlin
Arguments.of(DEFAULT_SIZE, BaseClass("Hello").shallowSize(),
                    "test for base class failed")
```

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePluginTest/src/test/kotlin/spbu/kotlin/shallow/plugin/ShallowSizeTest.kt
> +        fun sizeTest(): List<Arguments> {
Если сделать вот так, будет меньше отступов, что, наверное, лучше
```kotlin
fun sizeTest() = listOf( 
    ...
)

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    val function = clazz.functions.find { it.name.toString() == "shallowSize" }
"shallowSize" встречается тут и в 61ой строке, мб лучше в константу вынести

2022-04-17 12:23 UTC, Ythosa commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    val sum = clazz.properties.map { it.backingField?.type?.byteSize() ?: 0 }.sum()
`sum` не очень информативно звучит, может лучше `fieldsSize` или что-то типа того

2022-04-17 12:32 UTC, IgorErin commented on .github/workflows/main.yaml
> +      - name: Run detekt
Здравствуйте! Детект не находит исходники только в корневом проекте, потому что их нет, а в дочерних находит!
Или я не прав ?

2022-04-20 09:46 UTC, illided requested changes
Все ок, небольшие замечания.
Если дальше с Русланом будете на пару делать все баллы делим обоим на два :)

2022-04-20 09:46 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    require(function.noFormalParameters()) {"$FUNCTION_NAME has formal parameters"}
Лучше сразу искать функцию без параметров. 
Представь если пользователь сделал свою shallowSize с какими то параметрами, то мы возможно ее вытащим первой, хотя наша тоже где то есть

2022-04-20 09:46 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    require(function != null) { "shallowSize plugin cannot create a function body" }
А почему не может?

2022-04-20 09:46 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    require(function != null) { "shallowSize plugin cannot create a function body" }
Я к тому что хочется чуть подробнее почему не смог, а не просто "чот не получилось"

2022-04-20 11:24 UTC, Ythosa commented
@illided Вы слишком жестоки для человека, за которого сделали работу :(

2022-04-21 10:19 UTC, illided approved these changes
Теперь все нравится

2022-04-21 10:30 UTC, Ythosa commented
> Теперь все нравится

🐰

2022-05-02 09:51 UTC, nbirillo approved these changes

2022-05-02 09:51 UTC, merged

2022-05-08 12:25 UTC, Ythosa commented
![image](https://user-images.githubusercontent.com/10869361/167296007-5b2b2989-9ae9-415f-b34e-86e73abe47e0.png)